# Generated by Django 3.1.1 on 2020-11-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
