# Generated by Django 3.1.1 on 2020-11-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_has_variant'),
        ('checkout', '0004_auto_20201101_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size_color',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variants'),
        ),
    ]
