# Generated by Django 3.1.1 on 2020-11-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
    ]
