# Generated by Django 3.1.1 on 2020-10-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productdetail_product_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_colour_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcolour'),
        ),
    ]
