# Generated by Django 3.1.1 on 2020-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200929_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantities',
            name='name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
