# Generated by Django 3.1.1 on 2020-10-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdetail_product_colour_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_colour_id',
            new_name='colour',
        ),
    ]
