# Generated by Django 3.1.1 on 2020-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201005_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='initial_date',
        ),
        migrations.AddField(
            model_name='productsize',
            name='friendly_size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
