# Generated by Django 3.1.1 on 2020-10-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201005_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='friendly_size',
            new_name='friendly_size_name',
        ),
    ]
