# Generated by Django 3.1.1 on 2020-10-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductColour',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
    ]
