# Generated by Django 3.1.1 on 2020-10-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201005_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='size_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize'),
        ),
    ]
