# Generated by Django 3.1.1 on 2020-11-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201118_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_edition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
