# Generated by Django 3.1.1 on 2020-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201123_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_30_percent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
