# Generated by Django 3.1.1 on 2020-11-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='meida/'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.images'),
            preserve_default=False,
        ),
    ]
