# Generated by Django 3.1.1 on 2020-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20201127_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
