# Generated by Django 3.1.1 on 2020-12-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20201210_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='status',
        ),
    ]
