# Generated by Django 3.1.1 on 2020-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_variants_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=True, max_length=10),
        ),
    ]
